const projects = [
  {
    "Sr. No.": "1",
    "Project": "Singh's Office",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/01.%20Singh's%20Office/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/01.%20Singh's%20Office/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/01.%20Singh_s%20Office/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/01.%20Singh_s%20Office/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/01.%20Singh_s%20Office/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/01.%20Singh_s%20Office/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/01.%20Singh_s%20Office/6.png",
    ],
    "Typology": "Commerical Interiors ",
    "Location": "Bhopal, India",
    "Area": "1800",
    "Status": "On Going",
    "Year": "",
    "Description":
      "Mr. Singh's Office, where modern sophistication meets eclectic charm.Clean lines and sleek furniture are paired with vibrant textiles, natural materials, and artistic decor, creating a harmonious balance between professionalism and creativity.",
    "Client Name": "Mr. Sonu Singh",
  },
  {
    "Sr. No.": "2",
    "Project": "Agarwal's Office",
    "Typology": "Commerical Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/02.%20Agarwal's%20Office/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/02.%20Agarwal's%20Office/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/02.%20Agarwal's%20Office/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/02.%20Agarwal's%20Office/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/02.%20Agarwal's%20Office/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/02.%20Agarwal's%20Office/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/02.%20Agarwal's%20Office/6.png",
    ],
    "Location": "Bhopal, India",
    "Area": "1000",
    "Status": "On Going",
    "Year": "",
    "Description":
      "A classical and rustic office theme, seamlessly blending timeless elegance with rural charm. Rich wood finishes, antique furnishings, and vintage accents evoke a sense of heritage and sophistication. Thoughtfully curated decor elements add character to the space, embodying tradition and warmth. This office design harmonizes classical aesthetics with modern functionality, creating a welcoming environment for work and meetings.",
    "Client Name": "Mr. Nitesh Agarwal",
  },
  {
    "Sr. No.": "3",
    "Project": "Sai Infra's Site Office",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/03.%20Sai%20Infra's%20Site%20Office/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/03.%20Sai%20Infra's%20Site%20Office/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/03.%20Sai%20Infra's%20Site%20Office/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/03.%20Sai%20Infra's%20Site%20Office/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/03.%20Sai%20Infra's%20Site%20Office/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/03.%20Sai%20Infra's%20Site%20Office/5.png",
    ],
    "Typology": "Commerical Interiors ",
    "Location": "Bhopal, India",
    "Area": "2000",
    "Status": "On Going",
    "Year": "",
    "Description":
      "A functional and efficient site office for Sai Infra Serving as a project hub and meeting space, it maximizes workspace utility with ergonomic furniture and practical storage. Natural light enhances the welcoming atmosphere, while branded elements reflect the builder's identity and commitment to quality.",
    "Client Name": "Sai Infra Private Limited",
  },
  {
    "Sr. No.": "4",
    "Project": "Cyberautics ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/OFFICE/04.%20Cyberautics/7.png",
    ],
    "Typology": "Commerical Interiors ",
    "Location": "Indore, India",
    "Area": "2500",
    "Status": "On Going",
    "Year": "",
    "Description":
      "The Cyberautics office interior design fosters new perceptions and a unique learning environment. Our goal was to create a workplace that reflects the dynamic tech industry and provides a tranquil atmosphere for employees. Inspired by the tech landscape and the calming influence of nature, we integrated modern amenities with natural accents and cultural motifs, resulting in a harmonious blend of innovation and serenity.",
    "Client Name": "Cyberautics Private Limited",
  },
  {
    "Sr. No.": "5",
    "Project": "Motwani's Residence",
    "Typology": "Residential Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/01.%20Motwani's%20Residence/7.png",
    ],
    "Location": "Bhopal, India",
    "Area": "2400",
    "Status": "Completed",
    "Year": "2023",
    "Description":
      "Mr. Motwani's residence harmonizes modern and traditional themes, creating a captivating ambiance. Clean lines and sleek furnishings coexist with intricate patterns and timeless accents, reflecting his eclectic taste. The fusion of modern amenities with classic elements infuses each space with character and charm. Welcome to a home where the best of both worlds converge in perfect harmony.\"",
    "Client Name": "Mr. Ashish Motwani",
  },
  {
    "Sr. No.": "6",
    "Project": "Pramjeet Baga's Residence",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/7.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/8.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/02.%20Pramjeet%20Baga's%20Residence/9.png",
    ],
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "8000",
    "Status": "Completed",
    "Year": "2021",
    "Description":
      "Pramjeet Baga Ji's home boasts a delightful mix of colors and styles, creating a vibrant and eclectic ambiance. From bold hues to subtle tones, each space showcases a harmonious blend of diverse palettes. Modern furnishings seamlessly integrate with traditional accents, offering a unique and personalized aesthetic. Step into a world where every corner tells a story.",
    "Client Name": "Mr. Parmjeet Baga",
  },
  {
    "Sr. No.": "7",
    "Project": "Lalchandani's Residence",
    "Typology": "Residential Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/7.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/03.%20Lalchandani's%20Residence/8.png",
    ],
    "Location": "Bhopal, India",
    "Area": "2400",
    "Status": "Completed",
    "Year": "2024",
    "Description":
      "Embrace modern classical elegance at Avinash Lalchandani's residence. Clean lines intertwine with ornate detailing, evoking refined grandeur. This captivating ambiance harmonizes timeless tradition with contemporary sophistication. Welcome to a home where the past gracefully converges with the present.",
    "Client Name": "Mr. Avinash Lalchandani",
  },
  {
    "Sr. No.": "8",
    "Project": "Thakur's Residence",
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/04.%20Thakur's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/04.%20Thakur's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/04.%20Thakur's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/04.%20Thakur's%20Residence/3.png",
    ],
    "Area": "2800",
    "Status": "Ongoing",
    "Year": "",
    "Description":
      "Welcome to the Thakur Residence, where grand modernity reigns supreme. This architectural masterpiece seamlessly blends opulent grandeur with sleek contemporary design. Magnificent spaces adorned with luxurious finishes and cutting-edge amenities create an ambiance of unparalleled sophistication. Welcome to a residence where grandeur meets modernity in an awe-inspiring fusion.",
    "Client Name": "Mr. Rajesh Thakur",
  },
  {
    "Sr. No.": "9",
    "Project": "Narwani's Villa",
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "11000",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/05.%20Narwani's%20Villa/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/05.%20Narwani's%20Villa/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/05.%20Narwani's%20Villa/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/05.%20Narwani's%20Villa/3.png",
    ],
    "Status": "Ongoing",
    "Year": "",
    "Description":
      "Explore Mr. Hans Raj Narwani's residence, a pinnacle of contemporary luxury. This refined and elegant space showcases pristine lines, sumptuous finishes, and cutting-edge amenities. From the exquisite décor to the meticulous craftsmanship, each element radiates opulence and sophistication. Enter a realm of unparalleled refinement and indulgence, where modernity seamlessly intertwines with luxury.",
    "Client Name": "Mr. Hans Raj Narwani",
  },
  {
    "Sr. No.": "10",
    "Project": "Avanindra Sharma's Residence",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/06.%20Avanindra%20Sharma's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/06.%20Avanindra%20Sharma's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/06.%20Avanindra%20Sharma's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/06.%20Avanindra%20Sharma's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/06.%20Avanindra%20Sharma's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/06.%20Avanindra%20Sharma's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/06.%20Avanindra%20Sharma's%20Residence/6.png",
    ],
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "2800",
    "Status": "Completed",
    "Year": "2024",
    "Description":
      "This space embodies a playful fusion of clean geometry, Indian art, and experimental surface treatments, creating a vibrant and eclectic home, where Indian minimal classical design sets a distinctive tone. This elegant environment seamlessly blends traditional Indian aesthetics with minimalist sensibilities. ",
    "Client Name": "Mr Avanindra Sharma",
  },
  {
    "Sr. No.": "11",
    "Project": "Tiwari's Residence",
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "1800",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/07.%20Tiwari's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/07.%20Tiwari's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/07.%20Tiwari's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/07.%20Tiwari's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/07.%20Tiwari's%20Residence/4.png",
    ],
    "Status": "Completed",
    "Year": "2022",
    "Description":
      "Mr. Tiwari's residence is a celebration of modernity, featuring a dynamic interplay of colors, prints, and patterns. Each element, meticulously selected, contributes to the vibrant and energetic atmosphere. From bold hues to intricate designs, this space showcases the essence of contemporary design, offering a visually stimulating environment that captivates the senses.",
    "Client Name": "Mr. Abhay Tiwari",
  },
  {
    "Sr. No.": "12",
    "Project": "Naugrahiya's Residence",
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/7.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/8.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/08.%20Naugrahiya's%20Residence/9.png",
    ],
    "Area": "4000",
    "Status": "Ongoing",
    "Year": "",
    "Description":
      "At Naugrahiya's Residence, the wabi-sabi and boho elements intertwine seamlessly within its minimalist interior. Neutral beige and natural wooden tones form the backdrop, complemented by locally sourced furniture, handcrafted textile artwork, and ceramic wall installations. The ambiance is enhanced by the incorporation of eclectic boho elements, resulting in a harmonious and inviting space.",
    "Client Name": "Mr. Akash Naugrahiya",
  },
  {
    "Sr. No.": "13",
    "Project": "Dr. Akash's Recidence",
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "2500",
    "Status": "Completed",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/09.%20Dr.%20Akash's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/09.%20Dr.%20Akash's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/09.%20Dr.%20Akash's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/09.%20Dr.%20Akash's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/09.%20Dr.%20Akash's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/09.%20Dr.%20Akash's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/09.%20Dr.%20Akash's%20Residence/6.png",
    ],
    "Year": "2023",
    "Description":
      "Dr. Akash's home exudes a modern ambiance, characterized by sleek sophistication. Its design features crisp lines, minimalist aesthetics, and contemporary finishes. From its streamlined furnishings to its chic décor, every aspect contributes to the home's stylish and comfortable atmosphere. With an emphasis on simplicity and functionality",
    "Client Name": "Dr. Akash",
  },
  {
    "Sr. No.": "14",
    "Project": "Dr.Manoj's Residence",
    "Typology": "Residential Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/10.%20Dr.%20Manoj's%20Residence/7.png",
    ],
    "Location": "Bhopal, India",
    "Area": "2500",
    "Status": "Completed",
    "Year": "2023",
    "Description":
      "Dr. Manoj's home radiates modernity with its stylish design and contemporary allure. Its dynamic architecture, bold accents, and innovative finishes define the space. From its sophisticated furnishings to its chic embellishments, every element contributes to the home's modern aesthetic. With a focus on sleek, functional design, the residence offers a fashionable and inviting environment ",
    "Client Name": "Dr. Manoj Pandey",
  },
  {
    "Sr. No.": "15",
    "Project": "Godha's Residence",
    "Typology": "Residential Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/7.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/11.%20Godha's%20Residence/8.png",
    ],
    "Location": "Bhopal, India",
    "Area": "4000",
    "Status": "Ongoing",
    "Year": "",
    "Description":
      "The space is adorned with luxurious finishes, elegant furnishings, and opulent accents, evoking a sense of regal splendor. From majestic chandeliers to plush velvet upholstery, every detail reflects a timeless sophistication. With a perfect blend of contemporary design and royal grandeur, the residence offers an exquisite and distinguished living experience",
    "Client Name": "Mr. Vineet Godha",
  },

  {
    "Sr. No.": "17",
    "Project": "Nitin Jain's Residence",
    "Typology": "Residential Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/13.%20Nitin%20Jain's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/13.%20Nitin%20Jain's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/13.%20Nitin%20Jain's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/13.%20Nitin%20Jain's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/13.%20Nitin%20Jain's%20Residence/4.png",
    ],
    "Location": "Bhopal, India",
    "Area": "1400",
    "Status": "Completed",
    "Year": "2023",
    "Description":
      "Step into a world of sleek modernity, where clean lines, innovative materials, and bold accents converge to create a space that effortlessly reflects your sophisticated lifestyle and taste.",
    "Client Name": "Mr. Nitin Jain",
  },
  {
    "Sr. No.": "18",
    "Project": "Daga's Residence",
    "Typology": "Residential Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/14.%20Daga's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/14.%20Daga's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/14.%20Daga's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/14.%20Daga's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/14.%20Daga's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/14.%20Daga's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/14.%20Daga's%20Residence/6.png",
    ],
    "Location": "Bhopal, India",
    "Area": "2500",
    "Status": "Completed",
    "Year": "2018",
    "Description":
      "Indulge in chic contemporary living, where understated elegance and modern sophistication collide to create a space that's effortlessly stylish and endlessly inviting, reflecting your refined lifestyle.",
    "Client Name": "Mr. Pankaj Daga",
  },
  {
    "Sr. No.": "19",
    "Project": "Narendra Varyani's Residence",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/residential/15.%20Narendra%20Varyani_s%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/residential/15.%20Narendra%20Varyani_s%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/residential/15.%20Narendra%20Varyani_s%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/residential/15.%20Narendra%20Varyani_s%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/residential/15.%20Narendra%20Varyani_s%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/residential/15.%20Narendra%20Varyani_s%20Residence/5.png",
    ],
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "3500",
    "Status": "Completed",
    "Year": "2022",
    "Description":
      "Immerse yourself in progressive design, where innovative concepts and forward-thinking aesthetics redefine the boundaries of modern living, offering a dynamic and stylish environment tailored to your needs.",
    "Client Name": "Mr. Narendra Varyani",
  },
  {
    "Sr. No.": "20",
    "Project": "Keerti Berdia's Residence",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/16.%20Keerti%20Berdia's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/16.%20Keerti%20Berdia's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/16.%20Keerti%20Berdia's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/16.%20Keerti%20Berdia's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/16.%20Keerti%20Berdia's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/16.%20Keerti%20Berdia's%20Residence/5.png",
    ],
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "1800",
    "Status": "Completed",
    "Year": "2020",
    "Description":
      "Experience modern luxury at its finest in Mr. Keerti's residence, where sleek lines, opulent finishes, and refined details create an ambiance of refined sophistication and extravagance, tailored to elevate your living experience to new heights of comfort and elegance.",
    "Client Name": "Mr. Keerti Berdia",
  },
  {
    "Sr. No.": "23",
    "Project": "Shah's Residence",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/19.%20Shah's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/19.%20Shah's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/19.%20Shah's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/19.%20Shah's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/19.%20Shah's%20Residence/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/19.%20Shah's%20Residence/5.png",
    ],
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "1800",
    "Status": "Completed",
    "Year": "2020",
    "Description":
      "Elevate your lifestyle with contemporary elegance, where timeless design elements and refined aesthetics come together to create a space that's as luxurious as it is welcoming, offering modern comfort and sophistication tailored to your desires.",
    "Client Name": "Mr.Shah",
  },
  {
    "Sr. No.": "24",
    "Project": "Deepak Jain's Residence",
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/20.%20Deepak%20Jain's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/20.%20Deepak%20Jain's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/20.%20Deepak%20Jain's%20Residence/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/20.%20Deepak%20Jain's%20Residence/3.png",
    ],
    "Area": "1800",
    "Status": "Completed",
    "Year": "2020",
    "Description":
      "Colors and textures blend in varied compositions, accentuating the charm of this apartment. Vibrant hues juxtapose with soothing tones, while textures add depth and character to each space. From the soft warmth of wooden finishes to the bold statement of metallic accents, every detail contributes to a dynamic and visually captivating environment.",
    "Client Name": "Mr. Deepak Jain",
  },
  {
    "Sr. No.": "25",
    "Project": "Khare's Residence",
    "Typology": "Residential Interiors ",
    "Location": "Bhopal, India",
    "Area": "3000",
    "Status": "Ongoing",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/7.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/8.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/9.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RESIDENTIAL/21.%20Khare's%20Residence/6.png",
    ],
    "Year": "",
    "Description":
      "Indulge in comfort and style with our meticulously designed residential interiors for Mr. Khare of Bhopal. Each space reflects his unique personality and lifestyle, blending functionality with aesthetics. From cozy living rooms to elegant bedrooms, we create a harmonious and inviting atmosphere tailored to Mr. Khare's preferences. Welcome home to timeless elegance and modern comfort.",
    "Client Name": "Mr. Sunil Khare",
  },
  {
    "Sr. No.": "26",
    "Project": "Bhima Jewelers",
    "Typology": "Commercial Interiors ",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/01.%20Bhima%20Jewellers/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/01.%20Bhima%20Jewellers/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/01.%20Bhima%20Jewellers/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/01.%20Bhima%20Jewellers/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/01.%20Bhima%20Jewellers/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/01.%20Bhima%20Jewellers/5.png",
    ],
    "Location": "Jharkhand, India",
    "Area": "800",
    "Status": "Ongoing",
    "Year": "",
    "Description":
      "Experience the perfect blend of vintage charm and modern luxury at Bhima Jewelers.This space showcases luxury and style with meticulously crafted displays. Bold geometric patterns, rich materials, and opulent lighting create a captivating ambiance, perfectly highlighting our exquisite jewelry collections. ",
    "Client Name": "Mr. Sanjay Verma",
  },
  {
    "Sr. No.": "27",
    "Project": "Bakers at 169 degree",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/02.%20Bakers%20at%20169%20degree/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/02.%20Bakers%20at%20169%20degree/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/02.%20Bakers%20at%20169%20degree/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/02.%20Bakers%20at%20169%20degree/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/02.%20Bakers%20at%20169%20degree/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/02.%20Bakers%20at%20169%20degree/5.png",
    ],
    "Typology": "Commercial Interiors ",
    "Location": "Bhopal, India",
    "Area": "250",
    "Status": "Completed",
    "Year": "2023",
    "Description":
      "Immerse yourself in an oasis of sweetness, where the aroma of freshly baked treats and delightful pink hues enchant your senses. Vibrant energy and sweet delights fill every corner. Soft pinks, reminiscent of tropical sunsets, create a warm, inviting atmosphere, enhanced by playful touches of tropical flora and fauna.",
    "Client Name": "Mrs. Avani Patni Jain",
  },
  {
    "Sr. No.": "28",
    "Project": "Airolam Gallery",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/03.%20Airolam%20Gallery/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/03.%20Airolam%20Gallery/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/03.%20Airolam%20Gallery/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/03.%20Airolam%20Gallery/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/03.%20Airolam%20Gallery/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/03.%20Airolam%20Gallery/5.png",
    ],
    "Typology": "Commercial Interiors ",
    "Location": "Bhopal, India",
    "Area": "450",
    "Status": "Ongoing",
    "Year": "",
    "Description":
      "Welcome to Airolam Gallery, where design meets inspiration. Explore a world of creativity and innovation in surfacing solutions. As pioneers in the industry, Airolam showcases a diverse range of high-quality laminates and surfaces, curated to elevate every space.",
    "Client Name": "Airolam",
  },
  {
    "Sr. No.": "29",
    "Project": "Sogani Plywood & Vineer Studio",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/7.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/8.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/04.%20Sogani%20Plywood%20%26%20Veneer%20Studio/9.png",
    ],
    "Typology": "Commercial Interiors ",
    "Location": "Bhopal, India",
    "Area": "800",
    "Status": "Completed",
    "Year": "2020",
    "Description":
      "Step into a realm of contemporary elegance and rustic allure. Our premium plywood and veneer collection is showcased against sleek displays and comfortable lounge areas. Each meticulously crafted corner reflects our commitment to innovation, functionality, and timeless sophistication.",
    "Client Name": "Mr. Ayush & Abhash Sogani",
  },
  {
    "Sr. No.": "30",
    "Project": "Top 'n Town Kiosk",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/05.%20Top%20%26%20Town%20Kiosks/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/05.%20Top%20%26%20Town%20Kiosks/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/05.%20Top%20%26%20Town%20Kiosks/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/05.%20Top%20%26%20Town%20Kiosks/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/05.%20Top%20%26%20Town%20Kiosks/4.png",
    ],
    "Typology": "Commercial Interiors ",
    "Location": "Bhopal, India",
    "Area": "300",
    "Status": "Completed",
    "Year": "2021",
    "Description":
      "Discover modern glamour with art deco influences at Top & Town Kiosk. Sleek lines, geometric shapes, and luxurious materials create immersive showcases. Experience a fusion of heritage and innovation in a setting designed to captivate the senses.",
    "Client Name": "Top 'n Town Private Limited",
  },
  {
    "Sr. No.": "31",
    "Project": "House No. 230 - The Gourmet Kitchen & Bar",
    "Typology": "Commercial Interiors ",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/06.%20House%20No.%20230%20-%20The%20Gourmet%20Kitchen%20%26%20Bar/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/06.%20House%20No.%20230%20-%20The%20Gourmet%20Kitchen%20%26%20Bar/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/06.%20House%20No.%20230%20-%20The%20Gourmet%20Kitchen%20%26%20Bar/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/06.%20House%20No.%20230%20-%20The%20Gourmet%20Kitchen%20%26%20Bar/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/06.%20House%20No.%20230%20-%20The%20Gourmet%20Kitchen%20%26%20Bar/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/06.%20House%20No.%20230%20-%20The%20Gourmet%20Kitchen%20%26%20Bar/6.png"
    ],
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/RETAIL/06.%20House%20No.%20230%20-%20The%20Gourmet%20Kitchen%20%26%20Bar/1.png",
    "Location": "Bhopal, India",
    "Area": "2100",
    "Status": "Completed",
    "Year": "2021",
    "Description":
      "Welcome to House No. 230 - The Gourmet Kitchen & Bar, where interior design meets comedic flair! Step inside our whimsically styled space where culinary delights are served amidst playful decor and funky vibes. From vibrant colors to eccentric furnishings, every corner tells a story of culinary creativity and quirky charm.",
    "Client Name": "House No. 230 - The Gourmet Kitchen & Bar",
  },
  {
    "Sr. No.": "32",
    "Project": "Kasturi Resort",
    "imageURL":
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/1.png",
    "slidesURL": [
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/1.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/2.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/3.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/4.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/5.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/6.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/7.png",
      "https://raw.githubusercontent.com/adityaxtalk/interior-website-assets/main/INTERIOR%20WORKS/HOSPITALITY/01.%20Kasturi%20Resort/8.png",
    ],
    "Typology": "Commercial Interiors ",
    "Location": "Bhopal, India",
    "Area": "45000",
    "Status": "On Going",
    "Year": "",
    "Description":
      "Kasturi Resort is a sanctuary of luxury and relaxation, blending opulent interiors with lush greenery. Sophisticated design elements, elegant furnishings, and rich materials offer guests a tranquil and immersive experience. Expansive windows and indoor gardens connect guests to the serene outdoors. Every detail, from lavish suites to inviting common areas, exudes comfort and elegance, showcasing where luxury meets nature in perfect harmony.",
    "Client Name": "Mr. Jagdish Thakur",
  },
];

export default projects;
